=== yuvielle/cglib_j2ee_test/target/classes/note.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:attribute name="id" type="xs:ID"/>
        <xs:complexType>
        <xs:sequence>
            <xs:element name="model">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="object">
                        <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id"/>
                            <xs:element name="name"/>
                            <xs:element name="descript"/>
                            <xs:element name="price"/>
                            <xs:element name="count"/>
                            <xs:element name="url"/>
                            <xs:element name="images">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="id"/>
                                        <xs:element name="name"/>
                                        <xs:element name="url"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="firstname"/>
                            <xs:element name="lastname"/>
                            <xs:element name="username"/>
                            <xs:element name="password"/>
                        </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    </xs:element>
</xs:schema>

=== yuvielle/cglib_j2ee_test/out/artifacts/dep/WEB-INF/classes/shop.xml
<?xml version="1.0" encoding="UTF-8"?>
    <root xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="note.xsd">
        <model xs:id="shop_product">
            <object xs:id="1">
                <id>1</id>
                <name>test1</name>
                <descript>test5 descript1</descript>
                <price>67.90</price>
                <count>78</count>
                <url>test.ru</url>
                <images>
                    <id>1</id>
                    <id>8</id>
                </images>
            </object>
        </model>
        <model xs:id="shop_image">
            <object xs:id="1">
                <id>1</id>
                <name>test image</name>
                <url>http://test.ru</url>
            </object>
            <object xs:id="2">
                <id>2</id>
                <name>test image2</name>
                <url>http://test.ru</url>
            </object>
            <object xs:id="8">
                <id>8</id>
                <name>test image8</name>
                <url>http://test.ru</url>
            </object>
        </model>
        <model xs:id="shop_user">
            <object xs:id="1">
                <id>1</id>
                <firstname>testtt</firstname>
                <lastname>yuyuyuyu</lastname>
                <username>admin</username>
                <password>1234</password>
            </object>
        </model>
    </root>
